### PR TITLE
Switch to tinytest

### PR DESCRIPTION
**Pull request by mllg**

### CODE REVIEW

**Comment by mllg** [comment]
Tinytest not ready yet.

**Comment by mb706** [comment]
what is missing?

**Comment by mllg** [comment]
Sourcing files is technically possible, but strange things happen (e.g., loading a library is successful, but the namespace does not get attached properly). The alternative is to have "setup code" (setting options, disabling logger, loading packages) in each test file, which I find a bit tedious.

**Comment by mllg** [comment]
You can convince me otherwise. :wink:

**Pull request closed without merging**
